# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditCmdWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CmdEditWindow(object):
    def setupUi(self, CmdEditWindow):
        CmdEditWindow.setObjectName("CmdEditWindow")
        CmdEditWindow.resize(718, 535)
        self.centralwidget = QtWidgets.QWidget(CmdEditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CmdEditTable = QtWidgets.QTableWidget(self.centralwidget)
        self.CmdEditTable.setObjectName("CmdEditTable")
        self.CmdEditTable.setColumnCount(0)
        self.CmdEditTable.setRowCount(0)
        self.verticalLayout.addWidget(self.CmdEditTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        CmdEditWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CmdEditWindow)
        self.statusbar.setObjectName("statusbar")
        CmdEditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CmdEditWindow)
        QtCore.QMetaObject.connectSlotsByName(CmdEditWindow)

    def retranslateUi(self, CmdEditWindow):
        _translate = QtCore.QCoreApplication.translate
        CmdEditWindow.setWindowTitle(_translate("CmdEditWindow", "MainWindow"))
        self.addButton.setText(_translate("CmdEditWindow", "增加"))
        self.deleteButton.setText(_translate("CmdEditWindow", "删除"))
        self.saveButton.setText(_translate("CmdEditWindow", "保存"))
